# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import service_pb2 as service__pb2


class TemperatureServiceStub(object):
    """The service definition.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTemperature = channel.unary_unary(
                '/myservice.TemperatureService/GetTemperature',
                request_serializer=service__pb2.Empty.SerializeToString,
                response_deserializer=service__pb2.TemperatureResponse.FromString,
                )
        self.GetModelResult = channel.unary_unary(
                '/myservice.TemperatureService/GetModelResult',
                request_serializer=service__pb2.ModelRequest.SerializeToString,
                response_deserializer=service__pb2.ModelResponse.FromString,
                )


class TemperatureServiceServicer(object):
    """The service definition.
    """

    def GetTemperature(self, request, context):
        """Methods
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetModelResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TemperatureServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTemperature': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTemperature,
                    request_deserializer=service__pb2.Empty.FromString,
                    response_serializer=service__pb2.TemperatureResponse.SerializeToString,
            ),
            'GetModelResult': grpc.unary_unary_rpc_method_handler(
                    servicer.GetModelResult,
                    request_deserializer=service__pb2.ModelRequest.FromString,
                    response_serializer=service__pb2.ModelResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'myservice.TemperatureService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TemperatureService(object):
    """The service definition.
    """

    @staticmethod
    def GetTemperature(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.TemperatureService/GetTemperature',
            service__pb2.Empty.SerializeToString,
            service__pb2.TemperatureResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetModelResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/myservice.TemperatureService/GetModelResult',
            service__pb2.ModelRequest.SerializeToString,
            service__pb2.ModelResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
